https://docs.google.com/spreadsheets/d/1-NtxXkoQ-uV-B7T3vfxfv-hDAVf3UF4M/edit?usp=sharing&ouid=114951933348221158140&rtpof=true&sd=true

https://docs.google.com/spreadsheets/d/1E6jf5bBgCz_k_pY13iGoSLtd2vrQDnuV/edit?usp=sharing&ouid=114951933348221158140&rtpof=true&sd=true

Importer les deux fichiers : 
- Les commandes Odeis (df)
- Les conditions fournisseurs (df_cond)

In [3]:
import pandas as pd
import numpy as np

# ID du Google Sheet Commande Odeis
sheet_id = "1-NtxXkoQ-uV-B7T3vfxfv-hDAVf3UF4M"  # remplace par ton vrai ID
sheet_name = "EXPORT_EXCEL"  # adapte si ta feuille a un nom différent

url = f"https://docs.google.com/spreadsheets/d/{sheet_id}/gviz/tq?tqx=out:csv&sheet={sheet_name}"

#ID du Google Sheet Condition fournisseur
sheet_id2 = "1E6jf5bBgCz_k_pY13iGoSLtd2vrQDnuV" 
sheet_name2 = "ALL_GAMME"  

url2 = f"https://docs.google.com/spreadsheets/d/{sheet_id2}/gviz/tq?tqx=out:csv&sheet={sheet_name2}"


# Lire les données dans pandas
df = pd.read_csv(url)
df_cond = pd.read_csv(url2)

display(df.head(50))
display(df_cond.head(10))

,td_code,en_date_doc,fo_code,en_etat_facture,en_type_confie,en_num_doc,en_num_doc_ref,en_code,en_num_ext,en_frais_taxe,...,en_edi,td_color_w,num_fac,en_qte_doc,en_mt_doc,ed_etat,ed_code,en_date_paye,active,en_mt_suppl
0,CF,26/05/2025 00:00:00,101007.0,-1.0,A,11619.0,NaN,171173.0,CDE RIVIERE PK,NaN,...,0.0,16764671.0,CDE RIVIERE PK,50.0,"15971,13",NaN,NaN,07/07/2025 00:00:00,A,NaN
1,CF,15/05/2025 00:00:00,102004.0,-1.0,A,11618.0,NaN,170780.0,SAV 59884,NaN,...,0.0,16764671.0,SAV 59884,1.0,"22,96",NaN,NaN,26/05/2025 00:00:00,A,NaN
2,CF,15/05/2025 00:00:00,102044.0,0.0,A,11616.0,NaN,170772.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,1077.0,"40608,32",NaN,NaN,03/07/2025 00:00:00,A,NaN
3,CF,15/05/2025 00:00:00,102015.0,0.0,A,11615.0,NaN,170771.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,300.0,"23867,8",NaN,NaN,19/06/2025 00:00:00,A,NaN
4,CF,15/05/2025 00:00:00,102013.0,0.0,A,11614.0,NaN,170770.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,350.0,"20191,15",NaN,NaN,15/06/2025 00:00:00,A,NaN
5,CF,15/05/2025 00:00:00,102009.0,0.0,A,11613.0,NaN,170769.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,480.0,"17325,12",NaN,NaN,10/07/2025 00:00:00,A,NaN
6,CF,15/05/2025 00:00:00,102006.0,0.0,A,11612.0,NaN,170768.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,150.0,"9262,05",NaN,NaN,03/07/2025 00:00:00,A,NaN
7,CF,15/05/2025 00:00:00,102003.0,0.0,A,11611.0,NaN,170767.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,100.0,"32002,25",NaN,NaN,03/07/2025 00:00:00,A,NaN
8,CF,15/05/2025 00:00:00,102002.0,0.0,A,11610.0,NaN,170766.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,251.0,"13954,61",NaN,NaN,10/07/2025 00:00:00,A,NaN
9,CF,15/05/2025 00:00:00,102001.0,0.0,A,11609.0,NaN,170765.0,STK ALRT OR 5/25,NaN,...,0.0,16764671.0,STK ALRT OR 5/25,1405.0,"58157,42",NaN,NaN,03/07/2025 00:00:00,A,NaN
10,CF,15/05/2025 00:00:00,102017.0,-1.0,A,11608.0,NaN,170762.0,SAV 59896 -59923,NaN,...,0.0,16764671.0,SAV 59896 -59923,2.0,"56,16",NaN,NaN,30/05/2025 00:00:00,A,NaN
11,CF,15/05/2025 00:00:00,101002.0,-1.0,A,11606.0,NaN,170726.0,SAV 59910,NaN,...,0.0,16764671.0,SAV 59910,1.0,107,NaN,NaN,02/06/2025 00:00:00,A,NaN
12,CF,14/05/2025 00:00:00,101003.0,-1.0,A,11602.0,NaN,170616.0,AFTKPKQ225,NaN,...,0.0,16764671.0,AFTKPKQ225,23.0,"1472,17",NaN,NaN,10/06/2025 00:00:00,A,NaN
13,CF,14/05/2025 00:00:00,101007.0,-1.0,A,11601.0,NaN,170615.0,AFTKPKQ225,NaN,...,0.0,16764671.0,AFTKPKQ225,5.0,"370,11",NaN,NaN,10/06/2025 00:00:00,A,NaN
14,CF,12/05/2025 00:00:00,101003.0,0.0,A,11599.0,NaN,170486.0,STK ALRT PK 5/25,NaN,...,0.0,16764671.0,STK ALRT PK 5/25,50.0,"9260,03",NaN,NaN,12/06/2025 00:00:00,A,NaN
15,CF,12/05/2025 00:00:00,101006.0,0.0,A,11597.0,NaN,170478.0,STK ALRT 05/25,NaN,...,0.0,16764671.0,STK ALRT 05/25,30.0,5193,NaN,NaN,28/05/2025 00:00:00,A,NaN
16,CF,12/05/2025 00:00:00,101005.0,0.0,A,11596.0,NaN,170477.0,STK ALRT 05/25,NaN,...,0.0,16764671.0,STK ALRT 05/25,16.0,"1038,36",NaN,NaN,12/06/2025 00:00:00,A,NaN
17,CF,12/05/2025 00:00:00,101002.0,0.0,A,11594.0,NaN,170475.0,STK ALRT 05/25,NaN,...,0.0,16764671.0,STK ALRT 05/25,18.0,"3817,95",NaN,NaN,02/06/2025 00:00:00,A,NaN
18,CF,12/05/2025 00:00:00,101001.0,0.0,A,11593.0,NaN,170474.0,STK ALRT 05/25,NaN,...,0.0,16764671.0,STK ALRT 05/25,186.0,"35533,05",NaN,NaN,12/06/2025 00:00:00,A,NaN
19,CF,07/05/2025 00:00:00,105003.0,-1.0,A,11592.0,NaN,170370.0,CDE AF TK PACK,NaN,...,0.0,16764671.0,CDE AF TK PACK,30400.0,13220,NaN,NaN,10/06/2025 00:00:00,A,NaN
20,CF,05/05/2025 00:00:00,103136.0,0.0,A,11590.0,NaN,170251.0,AF TK MOODE 25,NaN,...,0.0,16764671.0,AF TK MOODE 25,1500.0,3237,NaN,NaN,03/06/2025 00:00:00,A,NaN
21,CF,05/05/2025 00:00:00,103134.0,0.0,A,11589.0,NaN,170250.0,AF TK MOODE 25,NaN,...,0.0,16764671.0,AF TK MOODE 25,1500.0,2160,NaN,NaN,06/06/2025 00:00:00,A,NaN
22,CF,05/05/2025 00:00:00,103001.0,0.0,A,11588.0,NaN,170249.0,AF TK MOODE 25,NaN,...,0.0,16764671.0,AF TK MOODE 25,8800.0,16303,NaN,NaN,09/06/2025 00:00:00,A,NaN
23,CF,02/05/2025 00:00:00,104030.0,0.0,A,11587.0,NaN,170215.0,CDE AF TK SET 25,NaN,...,0.0,16764671.0,CDE AF TK SET 25,9250.0,16650,NaN,NaN,06/06/2025 00:00:00,A,NaN
24,CF,29/04/2025 00:00:00,101003.0,0.0,A,11584.0,NaN,170183.0,CDE AF TK PK 25,NaN,...,0.0,16764671.0,CDE AF TK PK 25,89.0,"10864,44",NaN,NaN,03/06/2025 00:00:00,A,NaN
25,CF,29/04/2025 00:00:00,101007.0,0.0,A,11583.0,NaN,170180.0,CDE AF TK PK 25,NaN,...,0.0,16764671.0,CDE AF TK PK 25,13.0,"954,93",NaN,NaN,03/06/2025 00:00:00,A,NaN
26,CF,28/04/2025 00:00:00,101011.0,0.0,A,11571.0,NaN,170088.0,CDE AF TK HSI 25,NaN,...,0.0,16764671.0,CDE AF TK HSI 25,7.0,"684,72",NaN,NaN,30/05/2025 00:00:00,A,NaN
27,CF,28/04/2025 00:00:00,101006.0,1.0,A,11570.0,NaN,170087.0,CDE AF TK HSI 25,NaN,...,0.0,16764671.0,CDE AF TK HSI 25,10.0,"1869,32",NaN,NaN,23/05/2025 00:00:00,A,NaN
28,CF,28/04/2025 00:00:00,101002.0,0.0,A,11568.0,NaN,170085.0,CDE AF TK HSI 25,NaN,...,0.0,16764671.0,CDE AF TK HSI 25,40.0,"7449,52",NaN,NaN,02/06/2025 00:00:00,A,NaN
29,CF,28/04/2025 00:00:00,101012.0,-1.0,A,11566.0,NaN,169987.0,MJ-25000547,NaN,...,0.0,16764671.0,MJ-25000547,7.0,"837,93",NaN,NaN,25/04/2025 00:00:00,A,NaN
30,CF,15/04/2025 00:00:00,101003.0,-1.0,A,11555.0,NaN,169667.0,CLIENT MOODE,NaN,...,0.0,16764671.0,CLIENT MOODE,1.0,"99,06",NaN,NaN,05/05/2025 00:00:00,A,NaN
31,CF,11/04/2025 00:00:00,102046.0,0.0,A,11554.0,NaN,169579.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,60.0,"865,92",NaN,NaN,25/05/2025 00:00:00,A,NaN
32,CF,11/04/2025 00:00:00,102044.0,0.0,A,11553.0,NaN,169578.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,45.0,"2265,04",NaN,NaN,01/06/2025 00:00:00,A,NaN
33,CF,11/04/2025 00:00:00,102015.0,0.0,A,11552.0,NaN,169577.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,19.0,"1687,14",NaN,NaN,19/05/2025 00:00:00,A,NaN
34,CF,11/04/2025 00:00:00,102011.0,1.0,A,11550.0,NaN,169575.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,127.0,"1796,11",NaN,NaN,09/06/2025 00:00:00,A,NaN
35,CF,11/04/2025 00:00:00,102005.0,0.0,A,11548.0,NaN,169573.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,18.0,"312,71",NaN,NaN,09/06/2025 00:00:00,A,NaN
36,CF,11/04/2025 00:00:00,102002.0,0.0,A,11547.0,NaN,169572.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,74.0,"4209,54",NaN,NaN,06/06/2025 00:00:00,A,NaN
37,CF,11/04/2025 00:00:00,102001.0,0.0,A,11546.0,NaN,169571.0,REA OR VF Q3,NaN,...,0.0,16764671.0,REA OR VF Q3,142.0,"5406,32",NaN,NaN,01/06/2025 00:00:00,A,NaN
38,CF,11/04/2025 00:00:00,102024.0,0.0,A,11522.0,NaN,169546.0,REAORAFBSNEW,NaN,...,0.0,16764671.0,REAORAFBSNEW,12.0,"345,48",NaN,NaN,01/06/2025 00:00:00,A,NaN
39,CF,11/04/2025 00:00:00,102004.0,0.0,A,11518.0,NaN,169542.0,REAORAFBSNEW,NaN,...,0.0,16764671.0,REAORAFBSNEW,106.0,"3171,18",NaN,NaN,15/06/2025 00:00:00,A,NaN
40,CF,11/04/2025 00:00:00,102002.0,0.0,A,11517.0,NaN,169541.0,REAORAFBSNEW,NaN,...,0.0,16764671.0,REAORAFBSNEW,32.0,"2421,88",NaN,NaN,06/06/2025 00:00:00,A,NaN
41,CF,10/04/2025 00:00:00,101002.0,1.0,A,11508.0,NaN,169436.0,CDE AFBS HSI25,NaN,...,0.0,16764671.0,CDE AFBS HSI25,106.0,"28046,25",NaN,NaN,02/06/2025 00:00:00,A,NaN
42,CF,09/04/2025 00:00:00,101001.0,-1.0,A,11506.0,NaN,169395.0,SAV 59557,NaN,...,0.0,16764671.0,SAV 59557,3.0,16,NaN,NaN,31/03/2025 00:00:00,A,NaN
43,CF,09/04/2025 00:00:00,101001.0,-1.0,A,11505.0,NaN,169394.0,SAV 59481,NaN,...,0.0,16764671.0,SAV 59481,1.0,43,NaN,NaN,31/03/2025 00:00:00,A,NaN
44,CF,09/04/2025 00:00:00,101001.0,-1.0,A,11504.0,NaN,169393.0,SAV 59330,NaN,...,0.0,16764671.0,SAV 59330,4.0,171,NaN,NaN,31/03/2025 00:00:00,A,NaN
45,CF,09/04/2025 00:00:00,101001.0,-1.0,A,11503.0,NaN,169391.0,SAV 59308,NaN,...,0.0,16764671.0,SAV 59308,1.0,41,NaN,NaN,31/03/2025 00:00:00,A,NaN
46,CF,09/04/2025 00:00:00,101076.0,1.0,A,11502.0,NaN,169356.0,SAM-419,NaN,...,0.0,16764671.0,SAM-419,23.0,"1452,75",NaN,NaN,06/01/2025 00:00:00,A,NaN
47,CF,02/04/2025 00:00:00,102017.0,0.0,A,11497.0,NaN,169165.0,SAV 59177,NaN,...,0.0,16764671.0,SAV 59177,1.0,"104,4",NaN,NaN,19/05/2025 00:00:00,A,NaN
48,CF,27/03/2025 00:00:00,102010.0,-1.0,A,11475.0,NaN,168935.0,SAV 59205,NaN,...,0.0,16764671.0,SAV 59205,2.0,"74,43",NaN,NaN,15/05/2025 00:00:00,A,NaN
49,CF,26/03/2025 00:00:00,102032.0,0.0,A,11474.0,NaN,168872.0,REAORAFBSQ2-25,NaN,...,0.0,16764671.0,REAORAFBSQ2-25,6.0,"461,48",NaN,NaN,25/05/2025 00:00:00,A,NaN

,FO_CODE,GAMME,CONDITION DE PAIEMENTS,DELAIS DE PROD,RFA,FIXING METAL,PERTES
0,103019.0,ARGENT,30 %COMMANDE 70 %LIVRAISON,6 - 7 SEMAINES,NON,EXPE,0%
1,103021.0,ARGENT,30 %COMMANDE 70 %LIVRAISON,5 - 6 SEMAINES,NON,EXPE,0%
2,103022.0,ARGENT,30 %COMMANDE 70 %LIVRAISON,7 SEMAINES,NON,EXPE,0%
3,103027.0,ARGENT,AVANT EXPEDITION,7 SEMAINES,NON,EXPE,0%
4,103029.0,ARGENT,30 %COMMANDE 70 %LIVRAISON,6 - 7 SEMAINES,NON,EXPE,0%
5,13023.0,ARGENT,30 %COMMANDE 70 %LIVRAISON,NaN,NON,NaN,0%
6,105003.0,PACKAGING,30 %COMMANDE 70 %LIVRAISON,55 JOURS DE PROD,NON,NaN,0%
7,103001.0,PACKAGING,30 %COMMANDE 70 %LIVRAISON,35 jours,OUI,NaN,NaN
8,102002.0,OR,J30,8 semaines,OUI,A la cde,"0,00%"
9,102010.0,OR,AVANT EXPEDITION,6-8 semaines,NaN,A la facture,"5,00%"

In [4]:
print(f"Nombre de lignes: {df.shape[0]}, Nombre de colonnes: {df.shape[1]}")

Nombre de lignes: 63, Nombre de colonnes: 35

In [5]:
df.columns = df.columns.str.strip() # Supprimer les espaces des colonnes df
df_cond.columns = df_cond.columns.str.strip() # Supprime les espaces des colonnes df_cond

# Supprimer les colonnes inutiles du df (export auto)
df.drop(columns=
                ["en_type_confie",
                "fo_ref_cli",
                "td_color_w",
                "num_fac",
                "facture",
                "en_valeur_devise",
                "num_br",
                "en_num_livraison",
                "en_mt_suppl",
                "ed_etat",
                "en_num_doc_ref",
                "en_frais_taxe",
                "en_frais_non_taxe",
                "en_acompte",
                "en_escompte",
                "en_transf_bij_psion",
                "fo_edi_type",
                "en_edi",
                "ed_code",
                "active"],
        
        axis=1 ,inplace=True)

print(df.columns)
print(df_cond.columns)

Index(['td_code', 'en_date_doc', 'fo_code', 'en_etat_facture', 'en_num_doc',
       'en_code', 'en_num_ext', 'de_code', 'fo_raison_soc', 'num_com',
       'etat_lib', 'en_date2', 'en_qte_doc', 'en_mt_doc', 'en_date_paye'],
      dtype='object')
Index(['FO_CODE', 'GAMME', 'CONDITION DE PAIEMENTS', 'DELAIS DE PROD', 'RFA',
       'FIXING METAL', 'PERTES'],
      dtype='object')

In [6]:
# Afficher les valeurs nulles
nul_df = (df.isnull().sum())
nul_df_cond = (df_cond.isnull().sum())

In [7]:
# Renommer les colonnes
df.rename(columns={
    'td_code': 'type_commande',
    'en_date_doc': 'date_document',
    'fo_code': 'code_fournisseur',
    'en_etat_facture': 'etat_facture',
    'en_num_doc': 'numero_document',
    'en_code': 'Inconnu',
    'en_num_ext': 'raison_commande',
    'de_code': 'devise',
    'fo_raison_soc': 'nom_fournisseur',
    'num_com': 'numero_commande',
    'etat_lib': 'etat_document',
    'en_date2': 'date_livraison',
    'en_qte_doc': 'quantites',
    'en_mt_doc': 'montant',
    'en_date_paye': 'date_depart',
    }, inplace=True)


df_cond.rename(columns={
    'FO_CODE': 'code_fournisseur',
    }, inplace=True)

In [8]:
# Conversion des colonnes de dates colonne en datetime
df["date_document"] = pd.to_datetime(df["date_document"], format="%d/%m/%Y %H:%M:%S", dayfirst=True, errors="coerce")
df["date_livraison"] = pd.to_datetime(df["date_livraison"], format="%d/%m/%Y %H:%M:%S", dayfirst=True, errors="coerce")
df["date_depart"] = pd.to_datetime(df["date_depart"], format="%d/%m/%Y %H:%M:%S", dayfirst=True, errors="coerce")

In [9]:
# Merger mes deux df avec la colonne Condition de Paiements
df = df.merge(df_cond[["CONDITION DE PAIEMENTS", "code_fournisseur", "GAMME"]], on="code_fournisseur", how="left")

In [10]:
df.head()

,type_commande,date_document,code_fournisseur,etat_facture,numero_document,Inconnu,raison_commande,devise,nom_fournisseur,numero_commande,etat_document,date_livraison,quantites,montant,date_depart,CONDITION DE PAIEMENTS,GAMME
0,CF,2025-05-26,101007.0,-1.0,11619.0,171173.0,CDE RIVIERE PK,$,GLAMORO,11619.0,I,2025-07-11,50.0,"15971,13",2025-07-07,30 %COMMANDE 70 %LIVRAISON,PIQUE
1,CF,2025-05-15,102004.0,-1.0,11618.0,170780.0,SAV 59884,E,PEDRO ROMERO,11618.0,I,2025-06-06,1.0,"22,96",2025-05-26,J30,OR
2,CF,2025-05-15,102044.0,0.0,11616.0,170772.0,STK ALRT OR 5/25,E,RICHLINE ITALY SRL,11616.0,NaN,2025-07-08,1077.0,"40608,32",2025-07-03,60J,OR
3,CF,2025-05-15,102015.0,0.0,11615.0,170771.0,STK ALRT OR 5/25,E,OROLO SRL,11615.0,NaN,2025-06-24,300.0,"23867,8",2025-06-19,AVANT EXPEDITION,OR
4,CF,2025-05-15,102013.0,0.0,11614.0,170770.0,STK ALRT OR 5/25,E,DIBI S.p.A. Gold & Silver Ital,11614.0,NaN,2025-06-20,350.0,"20191,15",2025-06-15,AVANT EXPEDITION,OR

In [11]:
print(df["CONDITION DE PAIEMENTS"].value_counts())

CONDITION DE PAIEMENTS
J30                           20
AVANT EXPEDITION              17
30 %COMMANDE 70 %LIVRAISON    13
60J                           13
30% COMMANDE 70% LIVRAISON     6
30% DEPOSIT 70% J60            2
Name: count, dtype: int64

In [12]:
df["montant"] = df["montant"].str.replace(',', '.', regex=False)
df["montant"] = pd.to_numeric(df["montant"], errors="coerce")
print(df["montant"].dtype)

float64

In [13]:
df["CONDITION DE PAIEMENTS"].isnull().sum()
df = df.dropna(subset=["CONDITION DE PAIEMENTS"])
df

,type_commande,date_document,code_fournisseur,etat_facture,numero_document,Inconnu,raison_commande,devise,nom_fournisseur,numero_commande,etat_document,date_livraison,quantites,montant,date_depart,CONDITION DE PAIEMENTS,GAMME
0,CF,2025-05-26,101007.0,-1.0,11619.0,171173.0,CDE RIVIERE PK,$,GLAMORO,11619.0,I,2025-07-11,50.0,15971.13,2025-07-07,30 %COMMANDE 70 %LIVRAISON,PIQUE
1,CF,2025-05-15,102004.0,-1.0,11618.0,170780.0,SAV 59884,E,PEDRO ROMERO,11618.0,I,2025-06-06,1.0,22.96,2025-05-26,J30,OR
2,CF,2025-05-15,102044.0,0.0,11616.0,170772.0,STK ALRT OR 5/25,E,RICHLINE ITALY SRL,11616.0,NaN,2025-07-08,1077.0,40608.32,2025-07-03,60J,OR
3,CF,2025-05-15,102015.0,0.0,11615.0,170771.0,STK ALRT OR 5/25,E,OROLO SRL,11615.0,NaN,2025-06-24,300.0,23867.80,2025-06-19,AVANT EXPEDITION,OR
4,CF,2025-05-15,102013.0,0.0,11614.0,170770.0,STK ALRT OR 5/25,E,DIBI S.p.A. Gold & Silver Ital,11614.0,NaN,2025-06-20,350.0,20191.15,2025-06-15,AVANT EXPEDITION,OR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
70,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,3966.00,NaT,30 %COMMANDE 70 %LIVRAISON,PIQUE
71,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,9254.00,NaT,30 %COMMANDE 70 %LIVRAISON,PIQUE
72,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,9254.00,NaT,60J,PIQUE
73,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,9254.00,NaT,60J,PIQUE
74,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,9254.00,NaT,30 %COMMANDE 70 %LIVRAISON,PIQUE

In [14]:
paiements = []

for index, row in df.iterrows():
    fournisseur = row["nom_fournisseur"]
    condition = row["CONDITION DE PAIEMENTS"]
    montant_total = row["montant"]
    date_commande = row["date_document"]
    date_livraison = row["date_livraison"]
    numero_commande = row["numero_commande"]
    devise = row['devise']
    gamme = row['GAMME']
    code_four = row['code_fournisseur']

    
    condition = str(condition).strip().upper()

    if condition == "60J":
        date_paiement = date_livraison + pd.Timedelta(days=60)
        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_paiement,
            "montant": montant_total,
            "condition": condition,
            "devise": devise,
            "fournisseur": fournisseur,
            "gamme": gamme,
            "code_fournisseur": code_four
        })

    elif condition == "J30":
        date_paiement = date_livraison + pd.Timedelta(days=30)
        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_paiement,
            "montant": montant_total,
            "condition": condition,
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

    elif condition == "AVANT EXPEDITION":
        date_paiement = date_livraison
        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_paiement,
            "montant": montant_total,
            "condition": condition,
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

    elif condition in ["30% DEPOSIT 70% J60", "DEPOSIT 30% + J+60"]:
        montant_deposit = montant_total * 0.30
        montant_restant = montant_total - montant_deposit

        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_commande,
            "montant": montant_deposit,
            "condition": condition + " - deposit",
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

        date_solde = date_commande + pd.Timedelta(days=60)
        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_solde,
            "montant": montant_restant,
            "condition": condition + " - solde",
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

    elif condition in ["30 %COMMANDE 70 %LIVRAISON", "30% COMMANDE 70% LIVRAISON"]:
        # Hypothèse : même logique qu’un deposit 30%
        montant_deposit = montant_total * 0.30
        montant_restant = montant_total - montant_deposit

        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_commande,
            "montant": montant_deposit,
            "condition": condition + " - deposit estimé",
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

        date_solde = date_livraison
        paiements.append({
            "index_commande": index,
            "numero_commande": numero_commande,
            "date_paiement": date_solde,
            "montant": montant_restant,
            "condition": condition + " - solde",
             "devise": devise,
             "fournisseur": fournisseur,
             "gamme": gamme,
            "code_fournisseur": code_four
        })

    else:
        print(f"Condition non gérée : {condition}")

# Création du nouveau DataFrame avec les lignes de paiement
df_paiements = pd.DataFrame(paiements)

In [15]:
df_paiements

,index_commande,numero_commande,date_paiement,montant,condition,devise,fournisseur,gamme,code_fournisseur
0,0,11619.0,2025-05-26,4791.339,30 %COMMANDE 70 %LIVRAISON - deposit estimé,$,GLAMORO,PIQUE,101007.0
1,0,11619.0,2025-07-11,11179.791,30 %COMMANDE 70 %LIVRAISON - solde,$,GLAMORO,PIQUE,101007.0
2,1,11618.0,2025-07-06,22.960,J30,E,PEDRO ROMERO,OR,102004.0
3,2,11616.0,2025-09-06,40608.320,60J,E,RICHLINE ITALY SRL,OR,102044.0
4,3,11615.0,2025-06-24,23867.800,AVANT EXPEDITION,E,OROLO SRL,OR,102015.0
...,...,...,...,...,...,...,...,...,...
87,71,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN
88,72,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN
89,73,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN
90,74,NaN,NaT,2776.200,30 %COMMANDE 70 %LIVRAISON - deposit estimé,NaN,NaN,PIQUE,NaN
91,74,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN

In [16]:
# On crée les deux colonnes montant_eur et montant_usd en fonction de la devise
df_paiements["montant_eur"] = df_paiements.apply(
    lambda row: row["montant"] if row["devise"] == "E" else 0,
    axis=1
)

df_paiements["montant_usd"] = df_paiements.apply(
    lambda row: row["montant"] if row["devise"] == "$" else 0,
    axis=1)

In [17]:
df_paiements

,index_commande,numero_commande,date_paiement,montant,condition,devise,fournisseur,gamme,code_fournisseur,montant_eur,montant_usd
0,0,11619.0,2025-05-26,4791.339,30 %COMMANDE 70 %LIVRAISON - deposit estimé,$,GLAMORO,PIQUE,101007.0,0.00,4791.339
1,0,11619.0,2025-07-11,11179.791,30 %COMMANDE 70 %LIVRAISON - solde,$,GLAMORO,PIQUE,101007.0,0.00,11179.791
2,1,11618.0,2025-07-06,22.960,J30,E,PEDRO ROMERO,OR,102004.0,22.96,0.000
3,2,11616.0,2025-09-06,40608.320,60J,E,RICHLINE ITALY SRL,OR,102044.0,40608.32,0.000
4,3,11615.0,2025-06-24,23867.800,AVANT EXPEDITION,E,OROLO SRL,OR,102015.0,23867.80,0.000
...,...,...,...,...,...,...,...,...,...,...,...
87,71,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN,0.00,0.000
88,72,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN,0.00,0.000
89,73,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN,0.00,0.000
90,74,NaN,NaT,2776.200,30 %COMMANDE 70 %LIVRAISON - deposit estimé,NaN,NaN,PIQUE,NaN,0.00,0.000
91,74,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN,0.00,0.000

In [18]:
#Convertir les dates en semaines et en mois

df_paiements["semaine"] = df_paiements["date_paiement"].dt.to_period('W').astype(str)
df_paiements["mois"] = df_paiements["date_paiement"].dt.to_period('M').astype(str)

In [19]:
df_paiements

,index_commande,numero_commande,date_paiement,montant,condition,devise,fournisseur,gamme,code_fournisseur,montant_eur,montant_usd,semaine,mois
0,0,11619.0,2025-05-26,4791.339,30 %COMMANDE 70 %LIVRAISON - deposit estimé,$,GLAMORO,PIQUE,101007.0,0.00,4791.339,2025-05-26/2025-06-01,2025-05
1,0,11619.0,2025-07-11,11179.791,30 %COMMANDE 70 %LIVRAISON - solde,$,GLAMORO,PIQUE,101007.0,0.00,11179.791,2025-07-07/2025-07-13,2025-07
2,1,11618.0,2025-07-06,22.960,J30,E,PEDRO ROMERO,OR,102004.0,22.96,0.000,2025-06-30/2025-07-06,2025-07
3,2,11616.0,2025-09-06,40608.320,60J,E,RICHLINE ITALY SRL,OR,102044.0,40608.32,0.000,2025-09-01/2025-09-07,2025-09
4,3,11615.0,2025-06-24,23867.800,AVANT EXPEDITION,E,OROLO SRL,OR,102015.0,23867.80,0.000,2025-06-23/2025-06-29,2025-06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,71,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN,0.00,0.000,NaT,NaT
88,72,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN,0.00,0.000,NaT,NaT
89,73,NaN,NaT,9254.000,60J,NaN,NaN,PIQUE,NaN,0.00,0.000,NaT,NaT
90,74,NaN,NaT,2776.200,30 %COMMANDE 70 %LIVRAISON - deposit estimé,NaN,NaN,PIQUE,NaN,0.00,0.000,NaT,NaT
91,74,NaN,NaT,6477.800,30 %COMMANDE 70 %LIVRAISON - solde,NaN,NaN,PIQUE,NaN,0.00,0.000,NaT,NaT

In [31]:
#Convertir la colonne date de paiement en format date 
df_paiements["date_paiement"] = pd.to_datetime(df_paiements["date_paiement"], errors="coerce")
print(df_paiements["date_paiement"].dtype)

datetime64[ns]

In [20]:
paiements_par_semaine_euros = df_paiements.groupby("semaine")["montant_eur"].sum().reset_index()
paiements_par_mois_euros = df_paiements.groupby("mois")["montant_eur"].sum().reset_index()

paiements_par_semaine_usd = df_paiements.groupby("semaine")["montant_usd"].sum().reset_index()
paiements_par_mois_usd = df_paiements.groupby("mois")["montant_usd"].sum().reset_index()

In [21]:
print("Paiements par semaine en euros:")
display(paiements_par_semaine_euros)

print("Paiements par semaine en USD:")
display(paiements_par_semaine_usd)

print("\nPaiements par mois en euros:")
display(paiements_par_mois_euros)

print("\nPaiements par mois en USD:")
display(paiements_par_mois_usd)

Paiements par semaine en euros:

                  semaine  montant_eur
0   2025-03-24/2025-03-30         0.00
1   2025-04-07/2025-04-13         0.00
2   2025-04-14/2025-04-20         0.00
3   2025-04-28/2025-05-04      3568.44
4   2025-05-05/2025-05-11         0.00
5   2025-05-12/2025-05-18         0.00
6   2025-05-19/2025-05-25      1761.57
7   2025-05-26/2025-06-01       461.48
8   2025-06-02/2025-06-08         0.00
9   2025-06-09/2025-06-15      5621.10
10  2025-06-16/2025-06-22     20191.15
11  2025-06-23/2025-06-29     25945.45
12  2025-06-30/2025-07-06       368.44
13  2025-07-07/2025-07-13     64817.59
14  2025-07-14/2025-07-20      3483.89
15  2025-07-28/2025-08-03         0.00
16  2025-08-04/2025-08-10      2265.04
17  2025-08-11/2025-08-17     13954.61
18  2025-09-01/2025-09-07     40608.32
19                    NaT         0.00

Paiements par semaine en USD:

                  semaine  montant_usd
0   2025-03-24/2025-03-30      114.621
1   2025-04-07/2025-04-13     8413.875
2   2025-04-14/2025-04-20       29.718
3   2025-04-28/2025-05-04     7736.258
4   2025-05-05/2025-05-11     8926.242
5   2025-05-12/2025-05-18    11205.018
6   2025-05-19/2025-05-25    47844.140
7   2025-05-26/2025-06-01     5657.259
8   2025-06-02/2025-06-08    42024.687
9   2025-06-09/2025-06-15      259.077
10  2025-06-16/2025-06-22     6482.021
11  2025-06-23/2025-06-29     1412.924
12  2025-06-30/2025-07-06    53583.150
13  2025-07-07/2025-07-13    74002.830
14  2025-07-14/2025-07-20    55692.640
15  2025-07-28/2025-08-03    32673.890
16  2025-08-04/2025-08-10        0.000
17  2025-08-11/2025-08-17    35533.050
18  2025-09-01/2025-09-07        0.000
19                    NaT        0.000

Paiements par mois en euros:

      mois  montant_eur
0  2025-03         0.00
1  2025-04         0.00
2  2025-05      5791.49
3  2025-06     51757.70
4  2025-07     68669.92
5  2025-08     16219.65
6  2025-09     40608.32
7      NaT         0.00

Paiements par mois en USD:

      mois  montant_usd
0  2025-03      114.621
1  2025-04    15828.402
2  2025-05    73984.108
3  2025-06    50178.709
4  2025-07   215952.510
5  2025-08    35533.050
6  2025-09        0.000
7      NaT        0.000

In [22]:
paiements_par_gamme_euros = df_paiements.groupby("gamme")["montant_eur"].sum().reset_index()
paiements_par_gamme_usd = df_paiements.groupby("gamme")["montant_usd"].sum().reset_index()

In [23]:
print("Paiements par gamme en euros:")
display(paiements_par_gamme_euros)

print("\nPaiements par gamme en USD:")
display(paiements_par_gamme_usd)

Paiements par gamme en euros:

       gamme  montant_eur
0        HSI         0.00
1         OR    183047.08
2  PACKAGING         0.00
3      PIQUE         0.00

Paiements par gamme en USD:

       gamme  montant_usd
0        HSI    117904.06
1         OR    136694.53
2  PACKAGING     29523.00
3      PIQUE    107469.81

In [24]:
paiements_par_semaine_euros.to_csv("paiements_par_semaine_euros.csv", index=False)
paiements_par_semaine_usd.to_csv("paiements_par_semaine_usd.csv", index=False)
paiements_par_mois_euros.to_csv("paiements_par_mois_euros.csv", index=False)
paiements_par_mois_usd.to_csv("paiements_par_mois_usd.csv", index=False)
paiements_par_gamme_euros.to_csv("paiements_par_gamme_euros.csv", index=False)
paiements_par_gamme_usd.to_csv("paiements_par_gamme_usd.csv", index=False)
df_paiements.to_csv("paiements_fichiers.csv", index=False)